= Alan StdLib Italian: Definizioni
Tristano Ajmone <tajmone@gmail.com>
v0.7.16-Alpha, 2018-11-09: Alan 3.0beta6
=============================================================================
Adattamento italiano del modulo `lib_definitions.i` della
_ALAN Standard Library_ v2.1, (C) Anssi Räisänen, Artistic License 2.1.
Ad opera di Tristano Ajmone,  (C) 2018, Artistic License 2.1.
=============================================================================

// tag::custom_attributes[]
////
=============================================================================
Custom AsciiDoc Attributes for Doxter
=============================================================================
////

// Traduzione italiana degli attributi predefiniti di Asciidoctor:
include::attributes-it.adoc[tag=attributes-it]

// Definisci sostituzione di {X} con il carattere Unicode 'heavy check mark'
// (U+2714), usato nelle tabelle dei verbi:
:X: &#x2714;

// end::custom_attributes[]
// tag::restrizioni_verbali[]

== Le Restrizioni Verbali

La libreria dispone di un meccanismo di _restrizioni verbabli_ per limitare
in maniera controllata il tipo di azioni consentite al giocatore. Ad ogni
verbo della libreria corrisponde un attributo booleano nell'istanza `mia_AT`
del `blocco_definizioni` che determina se il verbo (o i verbi) associati ad
esso sono abilitati all'uso.

Nel corpo dei verbi definiti dalla libreria, prima di portare a compimento
l'azione viene sempre controllato se l'attributo di restrizione verbale cui
il verbo fa riferimento è abilitato o meno (ossia, se è `CAN` o `CAN NOT`),
e nel caso non lo fosse l'azione viene bloccata sul nascere, mostrando al 
giocatore il messaggio "`Non puoi farlo.`".

// end::restrizioni_verbali[]
// tag::restrizioni_tradotte[]
=== Elenco delle Restrizioni Verbali

Questo è l'elenco degli attributi di restrizioni verbali sinora tradotti:


[source,alan]
--------------------------------------------------------------------------------
  CAN abbandonare_partita.      ---> 'quit'
  CAN accendere.                ---> turn_on
  CAN alzarsi.                  ---> stand (up)
  CAN andare_a.                 ---> go_to
  CAN annusare.                 ---> smell
  CAN aprire.                   ---> open
  CAN aprire_con.               ---> open_with
  CAN ascoltare.                ---> listen + listen0 | ascolta0 + ascolta
  CAN aspettare.                ---> wait         (+ z)
  CAN assaggiare.               ---> taste        (+ lick)
  CAN attaccare.                ---> attack (+ beat, fight, hit, punch)
  CAN attaccare_con.            ---> attack_with
  CAN attraversare.             ---> climb_through
  CAN baciare.                  ---> kiss         (+ hug, embrace)
  CAN ballare.                  ---> dance
  CAN bere.                     ---> drink
  CAN bloccare.                 ---> lock
  CAN bloccare_con.             ---> lock_with
  CAN bruciare.                 ---> burn
  CAN bruciare_con.             ---> burn_with
  CAN bussare.                  ---> knock
  CAN cantare.                  ---> sing
  CAN caricare_partita.         ---> 'restore'
  CAN chiedere.                 ---> ask_for
  CAN chiudere.                 ---> close        (+ shut)
  CAN chiudere_con.             ---> close_with
  CAN comprare.                 ---> buy          (+ purchase)
  CAN consultare.               ---> consult
  CAN dare.                     ---> give
  CAN dire.                     ---> 'say'
  CAN dire_a.                   ---> say_to
  CAN domandare.                ---> ask (+ enquire, inquire, interrogate)
  CAN domandare_chi_sono_io.    ---> who_am_i
  CAN domandare_chi_è.          ---> who_is
  CAN domandare_cosa_sono_io.   ---> what_am_i
  CAN domandare_cosa_è.         ---> what_is
  CAN domandare_dove_mi_trovo.  ---> where_am_i
  CAN domandare_dove_è.         ---> where_is
  CAN dormire.                  ---> sleep        (+ rest)
  CAN entrare.                  ---> enter
  CAN esaminare.                ---> examine      (+ check, inspect, observe, x)
  CAN giocare_con.              ---> play_with
  CAN grattare.                 ---> scratch
  CAN gridare.                  ---> shout        (+ scream, yell)
  CAN guardare.                 ---> look         (+ gaze, peek)
  CAN guardare_attraverso.      ---> look_through
  CAN guardare_dietro.          ---> look_behind
  CAN guardare_fuori_da.        ---> look_out_of
  CAN guardare_in.              ---> look_in
  CAN guardare_sotto.           ---> look_under
  CAN guardare_su.              ---> look_up
  CAN guidare.                  ---> drive
  CAN indossare.                ---> wear
  CAN inventariare.             ---> i            (+ inv, inventory)
  CAN lanciare.                 ---> throw
  CAN lanciare_a.               ---> throw_to
  CAN lanciare_contro.          ---> throw_at
  CAN lanciare_in.              ---> throw_in
  CAN lasciare.                 ---> drop         (+ discard, dump, reject)
  CAN legare.                   ---> tie
  CAN legare_a.                 ---> tie_to
  CAN leggere.                  ---> read
  CAN liberare.                 ---> free         (+ release)
  CAN mangiare.                 ---> eat
  CAN mettere.                  ---> put          (+ lay, place)
  CAN mettere_contro.           ---> put_against
  CAN mettere_dietro.           ---> put_behind
  CAN mettere_in.               ---> put_in       (+ insert)
  CAN mettere_sotto.            ---> put_under
  CAN mettere_su.               ---> put_on
  CAN mettere_vicino.           ---> put_near
  CAN modalità_breve.           ---> brief
  CAN modalità_lunga.           ---> verbose
  CAN mordere.                  ---> bite         (+ chew)
  CAN mostrare.                 ---> 'show'       (+ reveal)
  CAN notificare.               ---> 'notify'
  CAN notificare_off.           ---> notify_off
  CAN notificare_on.            ---> notify_on
  CAN nuotare.                  ---> swim
  CAN nuotare_in.               ---> swim_in
  CAN parlare.                  ---> talk
  CAN parlare_con.              ---> talk_to      (+ speak)
  CAN pensare.                  ---> think
  CAN pensare_a.                ---> think_about
  CAN pregare.                  ---> pray
  CAN prendere.                 ---> take.        (+ carry, get, grab, hold, obtain)
  CAN prendere_da.              ---> take_from.   (+ remove from)
  CAN pulire.                   ---> clean        (+ polish, wipe)
  CAN raccontare.               ---> tell         (+ enlighten, inform)
  CAN ricominciare_partita.     ---> 'restart'
  CAN riempire.                 ---> fill
  CAN riempire_con.             ---> fill_with
  CAN rifare.                   ---> 'again'
  CAN ringraziamenti.           ---> credits      (+ acknowledgments, author, copyright)
  CAN riparare.                 ---> fix          (+ mend, repair)
  CAN rispondere.               ---> answer       (+ reply)
  CAN rispondere_No.            ---> 'no'
  CAN rispondere_Sì.            ---> yes
  CAN rompere.                  ---> break        (+ destroy)
  CAN rompere_con.              ---> break_with
  CAN salvare_partita.          ---> save
  CAN saltare.                  ---> jump
  CAN saltare_in.               ---> jump_in
  CAN saltare_su.               ---> jump_on
  CAN sbloccare.                ---> unlock
  CAN sbloccare_con.            ---> unlock_with
  CAN scavare.                  ---> dig
  CAN scendere_da.              ---> get_off
  CAN scrivere.                 ---> write
  CAN sdraiarsi.                ---> lie_down
  CAN sdraiarsi_in.             ---> lie_in
  CAN sdraiarsi_su.             ---> lie_on
  CAN sedersi.                  ---> sit (down)
  CAN sedersi_su.               ---> sit_on
  CAN seguire.                  ---> follow
  CAN sorseggiare.              ---> sip
  CAN spegnere.                 ---> turn_off
  CAN spingere.                 ---> push
  CAN spingere_con.             ---> push_with
  CAN spogliarsi.               ---> undress
  CAN strappare.                ---> tear (+ rip)
  CAN suonare.                  ---> play
  CAN svuotare.                 ---> 'empty'
  CAN svuotare_in.              ---> empty_in
  CAN svuotare_su.              ---> empty_on
  CAN tagliare.                 ---> cut
  CAN tagliare_con.             ---> cut_with
  CAN tirare.                   ---> pull
  CAN toccare.                  ---> touch (+ feel)
  CAN toccare_con.              ---> touch_with
  CAN togliersi_indumento.      ---> remove
  CAN trascrivere.              ---> 'script'
  CAN trascrivere_off.          ---> script_off
  CAN trascrivere_on.           ---> script_on
  CAN trovare.                  ---> find         (+ locate)
  CAN tuffarsi.                 ---> dive
  CAN tuffarsi_in.              ---> dive_in
  CAN uccidere.                 ---> kill         (+ murder)
  CAN uccidere_con.             ---> kill_with
  CAN usare.                    ---> 'use'
  CAN usare_con.                ---> use_with
  CAN vedere_punteggio.         ---> 'score'
  CAN vendere.                  ---> sell
  CAN versare.                  ---> pour
  CAN versare_in.               ---> pour_in
  CAN versare_su.               ---> pour_on
--------------------------------------------------------------------------------


// end::restrizioni_tradotte[]
// tag::intestazione[]
== L'Intestazione dell'Avventura (Banner)
Ogni avventura creata con la Libreria ha una sua _intestazione_ (detta anche
_banner_) contenente informazioni sull'avventura, il suo autore e le versioni
della libereria e del compilatore Alan utilizzati.

L'uso del banner è facoltativo.

L'instestazione viene creata dalla libreria tramite l'instanza
`intestazione` della classe `location`. L'espediente consiste nello sfruttate
la descrizione di questo luogo fittizio per visualizzare il testo del banner
all'inizio della partita tramite `DESCRIBE intestazione.`.


[source,alan]
--------------------------------------------------------------------------------
THE intestazione IsA LOCATION

    DESCRIPTION

    "$p" STYLE alert. SAY mia_AT:titolo. STYLE normal.

    IF sottotitolo OF mia_AT <> ""
      THEN "$n" SAY mia_AT:sottotitolo.
      END IF.

    "$n(C)" SAY mia_AT:autore. "," SAY mia_AT:anno. "."
    "$nAvventura realizzata con ALAN Interactive Fiction Language v3.0 beta6
     $nLibreria Standard Italiana v2.1"

    IF versione OF mia_AT <> "0"
      THEN "$nVersione" SAY mia_AT:versione.
      END IF.

    "$nTutti i diritti riservati."

END THE intestazione.

--------------------------------------------------------------------------------

La `DESCRIPTION` di `intestazione` agisce da template, e per riempire i
dettagli del testo del banner essa attingerà ai vari attributi di intestazione
presenti nell'istanza `mia_AT` dell'avventura.

=== Attributi dell'Intestazione
L'istanza `mia_AT` (del `blocco_definizioni`) espone all'autore degli
attributi per fornire i dettagli del banner che potrà (facoltativamente)
essere mostrato all'inizio della partita tramite il template dell'istanza
`intestazione`:


[source,alan]
--------------------------------------------------------------------------------
  HAS        titolo  "Nuova Avventura".
  HAS   sottotitolo  "".
  HAS        autore  "Il Mio Nome".
  HAS          anno   2018.
  HAS      versione  "1".
--------------------------------------------------------------------------------


// end::intestazione[]
// tag::todo[]
== TODO

Questa sezione contiene l'elenco delle cose da fare per ultimare l'adattamento
italiano del modulo delle definizioni.

// end::todo[]
// tag::restrizioni_non_tradotte[]
=== Restrizioni Verbali da Tradurre

Questo è l'elenco degli attributi verbali non ancora tradotti:

[source,alan]
--------------------------------------------------------------------------------
  CAN about.
  CAN catch.
  CAN climb.
  CAN climb_on.
  CAN 'exit'.
--CAN extinguish. ----------------> ** VERBO ELIMINATO **  (+ put out, quench)
  CAN fire.
  CAN fire_at.
--CAN get_up. --------------------> ** VERBO ELIMINATO **
  CAN hint.        -- (+ hints)
  CAN kick.
  CAN lift.
--CAN light. ---------------------> ** VERBO ELIMINATO **
--CAN look_at. -------------------> ** VERBO OBSOLETO (StdLib 1?) ** (= esamina)
  CAN pry.
  CAN pry_with.
--CAN put_down. ------------------> ** WASN'T USED! (SEE 'drop'!) **
  CAN rub.
  CAN search.
  CAN shake.
  CAN shoot.       -- (at)
  CAN shoot_with.
--CAN smell0. --------------------> ** ATTRIBUTO ELIMINATO **
  CAN squeeze.
  CAN stand_on.
--CAN switch. --------------------> ** VERBO ELIMINATO **
--CAN switch_on. -----------------> ** VERBO ELIMINATO **
--CAN switch_off. ----------------> ** VERBO ELIMINATO **
  CAN turn.        -- (+ rotate)
--------------------------------------------------------------------------------


// end::restrizioni_non_tradotte[]
// tag::todo_checklist[]
=== Check List

Lista della spesa per le varie cosucce da fare:


// end::todo_checklist[]

