= Alan StdLib Italian: Supplemento
Tristano Ajmone <tajmone@gmail.com>
v0.9.1-Alpha, 2018-11-25: Alan 3.0beta6
=============================================================================
Modulo supplementare della liberia italiana, non presente nell'originale
_ALAN Standard Library_ v2.1 di Anssi Räisänen.
Creato da Tristano Ajmone,  (C) 2018, Artistic License 2.1.
=============================================================================

// tag::custom_attributes[]
////
============================================================================
Custom AsciiDoc Attributes for Doxter
============================================================================
////

// Traduzione italiana degli attributi predefiniti di Asciidoctor:
include::attributes-it.adoc[tag=attributes-it]

// Definisci sostituzione di {X} con il carattere Unicode 'heavy check mark'
// (U+2714), usato nelle tabelle dei verbi:
:X: &#x2714;

// end::custom_attributes[]
// tag::intro[]
== Introduzione
Questo modulo della libreria (non presente nella StdLib originale inglese)
definisce vari sinonimi italiani per tradurre le <<Predefined Player Words>>
inglesi di Alan.
Si tratta di un modulo supplementare in quanto non sarà più necessario una
volta aggiunto l'italiano alle lingue supportate nativamente da Alan. Quando
ciò avverrà, questo modulo sarà rimosso.

// end::intro[]
// tag::player_words[]
== Predefined Player Words

Le _predefined Player Words_ sono dei gruppi di vocaboli del giocatore
predefiniti in Alan (ossia, integrate nel compilatore stesso). Le loro
definizioni variano in ciascuna delle lingue nativamente supportate da Alan.
La libreria italiana utilizza la lingua inglese come base di partenza.

Queste sono le _Player Words_ predefinite per la lingua inglese, suddivise
in gruppi di appartenenza:

--------------------------
ALL:   all everything
AND:   and then
BUT:   but except
THEM:  them
NOISE: go the
--------------------------

[NOTE]
============================================================================
Le _Player Words_ delle varie lingue sono definite nel file sorgente di Alan
`compiler/wrd.c` (riga 182).
============================================================================

// end::player_words[]
// tag::todo[]
== TODO

Questa sezione contiene l'elenco delle cose da fare per ultimare l'adattamento
italiano del modulo supplementare.

// end::todo[]
// tag::todo_checklist[]
=== Check-list generale

Lista della spesa per le varie cosucce da fare:



=== Check-list per Doxter

Finisci di trasformare commenti in documentazione Doxter:

* [ ] Doxterizza _CONJUNCTION WORDS_.
* [ ] Doxterizza _NOISE WORDS_.
* [ ] Doxterizza _ALL WORDS_.
* [ ] Doxterizza _EXCEPT WORDS_.
* [ ] Doxterizza _THEM WORDS_.
* [ ] Doxterizza _Preposizioni Articolate_.
// end::todo_checklist[]

