; ******************************************************************************
; *                                                                            *
; *                   TEST DELLE "PLAYER WORDS" IN ITALIANO                    *
; *                                                                            *
; ******************************************************************************
ovest

; ==============================================================================
;                              Testiamo "E" e "POI"                             
; ==============================================================================
prendi la pera POI prendi il mango
lascia la pera
prendi la pera E prendi le cigliege

; ==============================================================================
;                             Testiamo "TUTTO" ecc.                             
; ==============================================================================
lascia TUTTO

; NOTA: la forma "E POI" non è valida:
prendi la pera E POI prendi il mango
prendi il mango e prendi le cigliege

; ==============================================================================
;                         testiamo "TRANNE/ECCETTO" ecc.                        
; ==============================================================================
lascia TUTTO TRANNE le cigliege
; ------------------------------------------------------------------------------
; D'ora in poi useremo la formula magica XYZZY per raccogliere tutta la frutta!
; ------------------------------------------------------------------------------
xyzzy
lascia TUTTO ECCETTO le cigliege
xyzzy
lascia TUTTO ESCLUSE le cigliege
xyzzy
lascia TUTTO ESCLUSO il mango
xyzzy
lascia TUTTO ESCLUSI il mango e le cigliege
xyzzy
lascia TUTTO ESCLUSA la pera

