ovest

; testiamo "E" e "POI"
prendi la pera POI prendi il mango
drop la pera
prendi la pera E prendi le cigliege

; testiamo "TUTTO" ecc.
drop TUTTO

; NOTA: la forma "E POI" non è valida:
prendi la pera E POI prendi il mango
prendi il mango e prendi le cigliege

drop TUTTO TRANNE le cigliege
prendi la pera POI prendi il mango
drop TUTTO ECCETTO le cigliege
prendi la pera POI prendi il mango
drop TUTTO ESCLUSE le cigliege
