ovest

; testiamo "E" e "POI"
prendi la pera POI prendi il mango
drop la pera
prendi la pera E prendi le cigliege

; testiamo "TUTTO" ecc.
drop TUTTO

; NOTA: la forma "E POI" non è valida:
prendi la pera E POI prendi il mango
prendi il mango e prendi le cigliege

; testiamo "TRANNE/ECCETTO" ecc.
drop TUTTO TRANNE le cigliege
; D'ora in poi usiamo la formula magica XYZZY per raccogliere tutta la frutta
xyzzy
drop TUTTO ECCETTO le cigliege
xyzzy
drop TUTTO ESCLUSE le cigliege
xyzzy
drop TUTTO ESCLUSO il mango
xyzzy
drop TUTTO ESCLUSI il mango e le cigliege
xyzzy
drop TUTTO ESCLUSA la pera

